### ISSUE TITLE
Add plus/minus methods as aliases for add/subtract transformations

### ISSUE THREAD

**Issue by jamesdh** [pjazdzyk/unitility#10]
When using this library with Groovy, including `plus()` and `minus()` methods would allow one to more succinctly perform transformations, e.g.

```groovy
Distance d1 = Distance.ofMeters(10)
Distance d2 = Distance.ofMeters(100)
assert d1 + d2 == Distance.ofMeters(110)
// or even the following, which would default to using the unit of measurement that d1 was created with
assert d1 + 10 == Distance.ofMeters(20)
```

[Here's a blog post](https://kousenit.org/2013/09/03/making-java-groovy-operator-overloading/) with a bit more info and also the [official docs](https://docs.groovy-lang.org/2.5.0/html/documentation/core-operators.html#Operator-Overloading)

**Comment by pjazdzyk** [comment]
Hi James, thanks. I will check this article, and I will see to what extend this can be incorporated into the code.

**Comment by pjazdzyk** [comment]
@jamesdh Feature is implemented and it will be included in the next planned release. You can also test it now, using code from the branch: 
https://github.com/pjazdzyk/unitility/tree/feature/SNSUNI-46_add_frameworks_support
The next release will be a major change, project will be now multimodule and will include framework support for easier use in web applications.
In addition to plus/minus I have also refactored divide method, to allow similar functionality. I have done some simple tests with Groovy and it seems to work fine:

```groovy
        // Temperature examples
        def t1 = Temperature.ofCelsius(20)
        def t2 = Temperature.ofCelsius(10)
        def t3 = Temperature.ofKelvins(303.15) // =30 oC

        // Adding & subtracting: The same unit
        def t4 = t1 + t2
        def t5 = t1 - t2
        def t6 = t1 + 15.5;
        println t4 // Temperature{30.0°C}
        println t5 // Temperature{10.0°C}
        println t6 // Temperature{35.5°C}

        // Adding & subtracting: Different units of the same quantity, resolving to unit of the first addend.
        def t7 = t1 + t3
        def t8 = t1 - t3
        println t7 // Temperature{50.0°C}
        println t8 // Temperature{-10.0°C}

        // Multiply
        def t9 = t1 * t2
        def t10 = t1 * 2
        println t9 // will resolve to double = 200.0
        println t10 // Temperature{40.0°C}

        // Divide
        def t11 = t1 / t2
        def t12 = t1 / 2
        println t11 // will resolve to double = 2.0
        println t12 // Temperature{10.0°C}
 ```

**Comment by jamesdh** [comment]
You are awesome. Thank you for this! Love the project!

**Comment by pjazdzyk** [comment]
I am very happy you like my project!
New version - 2.0.0 has been released (it is not backward compatible, unfortunately). Changes from this issue are included in the new version - I hope it will work fine.
Spatial types I have plan to implement bit later, but I will do this. 
Thanks for your input! :)
